import Head from "next/head";
import Navigation from "../components/navigation";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navigation />
        <h1>Please pick a page</h1>
        <p>
          This is a proof-of-concept of a method of caching API requests in
          Next.JS.
        </p>
        <ul>
          <li>
            <a href="https://finetunepartners.com/insights/caching-api-requests-in-next-js/">
              Write-up
            </a>
          </li>
          <li>
            <a href="https://github.com/FinetuneDevelopment/cache-api-request">
              GitHub repo
            </a>
          </li>
        </ul>
      </main>
    </>
  );
}
